### ISSUE TITLE
Weird requirements and unclear instructions

### ISSUE THREAD

**Issue by pascalecu** [dashr9230/SA-MP#9]
Hello!

I noticed your README requires Delphi 7 and .NET 2003 and some other XP things. I understand those are _maybe_ for decompilation purposes, but what's stopping the project from doing the UI in (preferably) Lazarus or newer RAD Studio versions (such as 11.3 Community Edition)? Is there something I'm missing?

You should make it clearer what you mean by "building" (as opposed to compilation which is still TBD).

P.S.: I could help with the Delphi 7 side of things, can you tell me exactly why Delphi 7 is required (Lazarus can open D7 projects natively) and how I can help?

**Comment by dashr9230** [comment]
I thought the "matching decompilation" is already a loud and clear indication of what this repository is about, but seems like I was wrong.

Yes, the written requirements is for decompilation purposes only. And since this repository is intended to be free for everybody, you can do whatever you want with it at your own risk. In this case, using a newer or a different software.

To answer to the last question to why Delphi 7 is required, because of two reasons:
1. When it's compiled, the output executable assembly instructions will be the same as the original SA-MP executable one. If there are differences, then its more clear where and what needs to be changed.
2. Compatibility. I'm not familiar with RAD, but I have tried Lazarus (2.2.6) before, and build process always failed because of missing components and properties.

If you are planning to contribute to this project, then I'm going to tell you that right now. I'm not looking for reverse-engineered codes and/or building alternatives. For an example: If the provided code is faster or better alternative, and/or built with different compiler, then it's a reverse-engineered code. If the provided code compiled with the same compiler what originally was used and gives same executable result, then it's (matching) decompilation.

**Comment by pascalecu** [comment]
@dashr9230 Thanks for explaining, in that case I'll see how I can help.

Is there a "preferred" style guide or some other things I should know beforehand, besides what you told me?

And, if the decompilation efforts will ever be complete, do you plan on improving the code (making it faster, better etc.) or will you leave that to someone else?

**Comment by dashr9230** [comment]
Since compiling C/C++ code is lossy, there's no preferred coding style. If you have seen the code, you may have noticed it is inconsistent anyway. While it does uses the hungarian notation naming convention most of the time, but you'll see places where variables and function arguments that are in camel or snake cases. But if you really want my advice, then just follow the surrounding coding style, as I do just for authenticity.

Anything aside, I think there's nothing else you need to know other than what I said previously that this is decompilation project, and not reverse engineering. If this was a reverse engineering project, then it would not use .NET 2003, and Delphi 7 for building, and would have been rebuilt from scratch. And by decompilation, this also means that fixing bugs is not allowed, that will just alter the output of the file, however documenting them are appreciated. But I also mention here that, it is not vital to contribute with an actual output matching functions. Porting generated pseudocodes by IDA (or Ghidra) to C/C++ is more than enough for me, I can refactor the code and match the output later, but it will take some time.

As for your last question. After project completion, I leave the rest to someone else. I personally lost interest playing any GTA games, and it is not my jam running a community along with. So that's a no. I don't have a plans to improve the code or further developing it after I saw, many other SA-MP alternatives like RW-MP, SA-Network, RakMong Open Multiplayer, and so on... That is the reason why I discontinued developing SAMPC/SAMPE, if you may heard this name before.

**Comment by unkcs** [comment]
@dashr9230 You could create a define with the name FIX_BUGS and leave it disabled so as not to change the output.

**Comment by dashr9230** [comment]
It may not change the output for Windows binaries, however, it will for Linux binaries. And I am talking about assertions which contains the number of the line where `assert()` is placed. So I would rather separate fixes into a different branch, but fixing bugs is not the main focus here.

**Comment by unkcs** [comment]
@dashr9230 I agree with you, I hadn't thought about that part.


Anyway, do you have any goals of what to finish first if the client/server/bot?

**Comment by dashr9230** [comment]
I have no priority on which project should be completed first.
